#pragma once

#include "ops/add.h"
#include "ops/sub.h"
#include "ops/mul.h"
#include "ops/mullo.h"
#include "ops/fmadd.h"
#include "ops/fmsub.h"
#include "ops/neg.h"
#include "ops/mulhi.h"
#include "ops/div.h"
#include "ops/sqrt.h"
#include "ops/max.h"
#include "ops/min.h"
#include "ops/load.h"
#include "ops/store.h"
#include "ops/set1.h"